### ISSUE TITLE
Serie in Filmliste vorhanden, wird aber nicht in DB geschrieben

### ISSUE THREAD

**Issue by cc13com** [bablokb/mtv_cli#19]
Hallo,

gerade gibt es die Serie "Höllgrund", welche nach meiner Recherche auch in der Filmliste aufgeführt wird. Wenn ich über die Konsole oder Weboberfläche danach suche, bekomme ich 2 Treffer. Es müssten mindestens 8 sein.

Ich habe ein paar "Debug" Anweisungen in "split_content" aufgenommen und kann sehen, dass dort auch mehr als zwei mal der gewünschte Suchbegriff auftaucht. Nur scheinbar wird es nicht in die Datenbank geschrieben.

Wo liegt der Fehler?

**Comment by bablokb** [comment]
Ich bekomme 38 Treffer, wobei vier davon kurze Clips wohl über eine beteiligte Schauspielerin sind. Datenstand ist von gerade eben, aber mit den Daten von vor drei Tagen habe ich das auch  so gehabt.

**Comment by cc13com** [comment]
Folgende Schritte habe ich durchgeführt:

In _mtv_filmdb.py_ habe ich in der Funktion _insert_film_ folgenden Code eingefügt:

```
if 'Höllgrund' in record:
      self.trefferrecord += 1
      Msg.msg("INFO","Treffer Sätze (gesamt):      %d" % self.trefferrecord)

[INFO] [2022-10-25 12:38:29] Treffer Sätze (gesamt):      16

```

Um vor dem Import in die Datenbank zu schauen, wie viele Treffer in der Filmliste sind. Aktuell bekomme ich 16 Treffer. Also schon mal mehr, als die zwei auf der Console bei:

```
/usr/local/bin# mtv_cli.py -Q "Höllgrund"
Sender |Thema          |Datum   |Dauer   |Titel
______________________________________________________________________________________________
ARD    |Höllgrund      |11.10.22|03:01:55|Pen & Paper | Der Schützenverein: Eine Höllgrund-Ges
SWR    |Höllgrund      |11.10.22|03:01:55|Pen & Paper | Der Schützenverein: Eine Höllgrund-Ges
```

In der Datenbank sind dann nur die o.g. zwei Treffer, was ich mit deinem DB-Viewer-Tool auch nochmal geprüft habe, indem ich die Datenbank-Datei darin geöffnet und mit dem Begriff gesucht habe. Was mich wundert, ist, dass die Datenbank-Datei nur 22.908.928 Bytes groß ist. Die Filmliste entpackt über 300 MB. Natürlich kann es sein, dass die DB gut komprimiert.

Die fehlenden 14 Einträge gehen also auf dem Weg in der _rec2FilmInfo_ verloren.

**Comment by bablokb** [comment]
Ich bekomme nach wie vor 38 Einträge. Bitte mal die /etc/mtv_cli.conf ansehen. Dort gibt es zwei Parameter, die zur Filterung beitragen:

    DATE_CUTOFF: 60
    DAUER_CUTOFF: 5

Vielleicht ist da ja was anders gesetzt.

**Comment by cc13com** [comment]
DATE_CUTOFF ist die Lösung. Ich hatte den Standardwert 30 verwendet.

Dank dir @bablokb
