### ISSUE TITLE
Titel mit Sonderzeichen werden nicht geladen

### ISSUE THREAD

**Issue by cc13com** [bablokb/mtv_cli#21]
Hallo,

Sowohl über die Weboberfläche, als auch auf der Konsole kann ich nach "A Good Girl's Guide to Murder" suchen und finde die Serie auch. Wenn ich sie dann zum Download vormerke und diesen starte, werden die Episoden aber nicht heruntergeladen.

Kann es am Apostroph im Namen hängen?

Grüße,
Carsten

**Comment by bablokb** [comment]
Ich befürchte, ja. In der Datei /etc/mtv_cli.conf gibt es die Zeile:

    CMD_DOWNLOADS: wget -q -c -O '{ziel}' '{url}'

Du könntest mal versuchen, hier das Apostroph durch Hochkomma zu ersetzen. Dann scheitern natürlich andere Titel.

Eventuell ändere ich das mal generell und ersetzte das Apostroph durch einen Unterstrich. Das wäre eine Zeile in `bin/mtv_download.py`.

**Comment by cc13com** [comment]
Ja, wenn ich Apostroph durch Hochkomma ersetze, funktioniert der Download.

Danke!
