### ISSUE TITLE
Webinterface, Suche nur ohne Umlaute

### ISSUE THREAD

**Issue by sofad** [bablokb/mtv_cli#3]
Umlaute funktionieren nicht bei der Suche im Webinterface (IP:8026  > Suchen > Global).

zb: "Tagebücher"
![suche](https://user-images.githubusercontent.com/3661870/37650840-751cbeea-2c36-11e8-83e3-daaf7b0a4396.png)

liefert kein Ergebnis
![0](https://user-images.githubusercontent.com/3661870/37650860-89323950-2c36-11e8-9236-52a470af239c.png)

Die Suche per Kommandozeile liefert Ergebnisse:

![kommandozeile](https://user-images.githubusercontent.com/3661870/37650939-c1303690-2c36-11e8-9894-902e26248e75.png)

Verwendete Hardware
Raspberry Pi Zero W Rev 1.1

Verwendete Software
Debian 9.3
Linux raspberrypi 4.9.80+ #1098 Fri Mar 9 18:51:28 GMT 2018 armv6l GNU/Linux

**Comment by bablokb** [comment]
Danke für den Hinweis, muss ich untersuchen. Die eigentliche Suchfunktion in der Datenbank ist bei mtv_cli.py und mvt_web.py identisch. Wahrscheinlich gehen die Umlaute auf dem Weg vom Browser zum Server verloren bzw. werden irgendwie encodiert.

**Comment by bablokb** [comment]
Mit Commit 4d1903b323abccac72075af0d5b7249f96d7cd78 behoben.
