### ISSUE TITLE
`mtv_cli -A auto` funktioniert nicht aufgrund fehlerhafter URLs

### ISSUE THREAD

**Issue by MaxG87** [bablokb/mtv_cli#6]
Ich habe `mtv_cli` auf meinem RasberryPi 4 installiert. Ich wollte dann mittels `mtv_cli -A` die Filmdatenbank initialisieren. Dies schlug mehrfach fehl mit folgender Fehlermeldung:

```
[INFO] [2021-06-29 10:49:07] Erzeuge /home/pi/.mediathek3/filme.sqlite aus http://verteiler4.mediathekview.de/Filmliste-akt.xz                                                                                                                  │············
[ERROR] [2021-06-29 10:49:07] Update der Filmliste gescheitert. Fehler: <urlopen error [Errno -2] Name or service not known>                                                                                                                    │············
```

Die gleiche Fehlermeldung ergibt sich für `verteiler2`, `verteiler3`, `verteiler4` und `verteiler6`. Die Aktualisierung funktioniert für `verteiler1`.

Leider kenne ich mich mit den Interna von MediathekView nicht gut genug aus, um dieses Problem selbst zu beheben.

**Comment by MaxG87** [comment]
Es scheint, als wurde seit im Juni 2020 alle Verteiler abgeschaltet. Es gibt einen neuen Link zu den Filmlisten:  https://liste.mediathekview.de .

Quelle: https://forum.mediathekview.de/topic/3508/aktuelle-verteiler-und-filmlisten-server

**Comment by bablokb** [comment]
Bitte mal mit dem next-Branch testen. Dort habe ich schon ein par Änderungen eingebaut, die in diese Richtung zielen.

Danke

**Comment by bablokb** [comment]
Mit https://github.com/bablokb/mtv_cli/pull/11 erledigt
