### ISSUE TITLE
Minimale Python-Version?

### ISSUE THREAD

**Issue by MaxG87** [bablokb/mtv_cli#9]
Welches ist denn die minimale Python-Version, die unterstützt werden soll? Ich hätte gerne ein paar Konstrukte modernisiert, war mir aber nicht sicher, ob diese dann vielleicht zu modern gewesen wären. (f-strings z.b.).

Mein Raspberry Pi 4 läuft mit Raspbian. Dort ist Python 3.7 verfügbar.

**Comment by bablokb** [comment]
Ich schlage folgendes vor: wir schauen, dass die aktuellen Änderungen im next-Branch "fertig" sind, der kommt dann in den Master-Zweig. Dann erstelle ich einen python3.x-Branch (ich habe keine Ahnung, auf welchem genauen Level x der Code ist), der dann eingefroren ist. Im next-Branch kommen dann die Modernisierungen, die 3.7ff benötigen. I.a.R. möchte ich aber bei dem Sprachlevel bleiben, der vom aktuellen PiOS unterstützt wird.

Mein Server (Odroid-HC1 unter Armbian-Stretch) läuft übrigens noch mit 3.5.3, dort habe ich SSL-Probleme (mtv_cli.py -A geht gar nicht mehr). Da müsste ich sowieso ran.

**Comment by MaxG87** [comment]
Das klingt sehr gut.
